[remote.github]
owner = "DoubledDoge"
repo = "splithappens"

[changelog]
header = ""
body = """
## What's Changed\n
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/DoubledDoge/splithappens/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}
"""
trim = true
footer = "{% if previous.version %}**Full Changelog**: https://github.com/DoubledDoge/splithappens/compare/{{ previous.version }}...{{ version }}{% endif %}"

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat!", group = "💥 Breaking Changes" },
    { message = "^feat",  group = "🚀 Features" },
    { message = "^fix",   group = "🐛 Bug Fixes" },
    { message = "^docs",  group = "📚 Documentation" },
    { message = "^style", group = "🎨 Styling & Theming" },
    { message = "^perf",  group = "🚅 Performance" },
    { message = "^chore|^refactor|^build|^ci", group = "🧹 Maintenance" },
    { message = "^test", group = "✅ Tests" }
]
filter_commits = false
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "newest"